const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true, channel:"chrome"});
 const page=await browser.newPage({viewport:{width:1280,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8765');
 await page.locator('#chatFab').click();
 await page.locator('#profileSelect').selectOption('student');
 await page.locator('#chatInput').fill('My lesson will not launch. It displays error 42.');
 await page.locator('#chatSend').click();
 await page.getByRole('button',{name:'MCeLE',exact:true}).click();
 await page.getByRole('button',{name:'EPME4000',exact:true}).click();
 await page.locator('#chatSend').waitFor({state:'visible'});
 await page.waitForFunction(()=>!document.getElementById('chatSend').disabled);
 await page.locator('#chatInput').fill('I restarted my computer and still see the same error.');
 await page.locator('#chatSend').click();
 await page.waitForFunction(()=>!document.getElementById('chatSend').disabled);
 await page.locator('#btnSupport').click();
 await page.locator('#ticketPage').waitFor({state:'visible'});
 assert.equal(await page.locator('#ticketUsername').inputValue(),'username.student');
 assert.equal(await page.locator('#ticketCourse').inputValue(),'EPME4000');
 assert.equal(await page.locator('#ticketType').inputValue(),'MCeLE');
 assert.match(await page.locator('#ticketDescription').inputValue(),/restarted my computer/);
 await page.screenshot({path:require('node:path').join(require('node:os').tmpdir(),'mcele-jira-ticket.png'),fullPage:true});
 await page.locator('#ticketSummary').fill('Edited summary for review');
 await page.getByRole('button',{name:'Create mock ticket',exact:true}).click();
 assert.match(await page.locator('#ticketConfirmation').innerText(),/Nothing was sent/);
 await page.locator('#ticketBack').click();
 await page.locator('#chatInput').waitFor({state:'visible'});
 assert.match(await page.locator('#chatBody').innerText(),/error 42/);
 await page.locator('#profileSelect').selectOption('instructor');
 await page.waitForFunction(()=>!document.getElementById('chatSend').disabled);
 assert.doesNotMatch(await page.locator('#chatBody').innerText(),/error 42/);
 assert.equal(await page.locator('#ticketDescription').inputValue(),'');
 assert.equal(await page.locator('#courseSelect').inputValue(),'');
 assert.equal(await page.locator('#systemSelect').inputValue(),'');
 await page.locator('#chatInput').fill('The assignment in my course is missing.');
 await page.locator('#btnSupport').click();
 await page.getByRole('button',{name:'Moodle',exact:true}).click();
 await page.getByRole('button',{name:'Course not listed',exact:true}).click();
 await page.locator('#otherCourse').fill('CUSTOM101');
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.locator('#ticketPage').waitFor({state:'visible'});
 assert.equal(await page.locator('#ticketUsername').inputValue(),'username.instructor');
 assert.equal(await page.locator('#ticketCourse').inputValue(),'CUSTOM101');
 assert.equal(await page.locator('#ticketType').inputValue(),'Moodle');
 assert.doesNotMatch(await page.locator('#ticketDescription').inputValue(),/error 42/);
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:require('node:path').join(require('node:os').tmpdir(),'mcele-jira-ticket-mobile.png'),fullPage:true});
 assert.equal(await page.evaluate(()=>document.getElementById('ticketPage').scrollWidth<=window.innerWidth),true);
 assert.deepEqual(errors,[]);
 console.log('Browser checks passed: site then course, chat history prefill, editable mock creation, back navigation, profile isolation, unlisted course, ticket before chat, mobile layout.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
